### ISSUE TITLE
Difficulty 'normal' is not preselected when starting the game, but is the default 

### ISSUE THREAD

**Issue by Jasperav** [RensArts/chad-bird-game#10]
See this image, no difficulty is preselected but normal should be the default:
![image](https://github.com/RensArts/chad-bird-game/assets/20363565/216142cb-777f-4c99-9636-6cdf4d75b64d)

**Comment by RensArts** [comment]
Fixed, the button will now be selected when the game loads in and be set to the difficulty you have selected before.
