### ISSUE TITLE
'dist' is root dir

### ISSUE THREAD

**Issue by Jasperav** [RensArts/chad-bird-game#2]
Not very logical to have a dir as root and no other files/dirs, just remove the whole dist dir

**Comment by RensArts** [comment]
normally my files for electron packager are outside dist, at the moment i have this not installed hence why it's an empty file

**Comment by Jasperav** [comment]
I don't understand what you mean, this is how the game now looks:

![image](https://github.com/RensArts/chad-bird-game/assets/20363565/db052cb1-b4da-4623-a1e3-34ed4e87971a)

so 'dist' is root, but it makes no sense, all files/dirs inside `dist` should be the root
