### ISSUE TITLE
Increase velocity by default, lower the speed?

### ISSUE THREAD

**Issue by Jasperav** [RensArts/chad-bird-game#9]
Maybe I am used to the flappy bird style, but I think the game is just a little bit to quick, what about increasing the velocity when you click (Chad will fly higher), lower the speed and increase the space between the pipes vertically and more distance between the pipes? Or I am just really bad at the game because I can not reach a high score :(

**Comment by RensArts** [comment]
When you tested the game the hitboxes where very big and that made it way harder than it needed to be, anyways i lowered the speed by a little bit and the hitboxes are significantly smaller and more consistent now. Thanks!
